language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && ENABLE_COVERAGE=ON"
    - os: osx
      osx_image: xcode9.2 
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir -p build && cd build
  - |
    if [ "$ENABLE_COVERAGE" == "ON" ]; then
      cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON ..
    else
      cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON ..
    fi

script:
  - cmake --build . # Build the code
  - ctest --verbose # Run tests
  - sudo make install # Install the necessary files

after_success:
  - |
    if [ "$ENABLE_COVERAGE" == "ON" ]; then
      bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    fi
