dist: trusty
sudo: require
language: cpp
compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
            - gcc-7
            - cmake

script:
    - g++-7 --version && gcc-7 --version && cmake --version # >=GCC/G++7.2 and >= CMake 3.1
    - export CC=gcc-7
    - export CXX=g++-7
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make
    - make test