language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && BUILD_TYPE=Debug && CPPCHECK_ANALYSIS=ON"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && BUILD_TYPE=Release"
    - os: osx
      osx_image: xcode9.2 
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && BUILD_TYPE=Debug"
    - os: osx
      osx_image: xcode9.2 
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && BUILD_TYPE=Release"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir -p build && cd build
  - |
    if [ "$CPPCHECK_ANALYSIS" == "ON" ]; then
      cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=ON -DCPPCHECK_ANALYSIS=ON ..
    else
      cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=ON ..
    fi

script:
  - cmake --build . # Build the code
  - ctest --verbose # Run tests
  - |
    if [ "$CPPCHECK_ANALYSIS" == "ON" ]; then
      make cppcheck
    fi
  - sudo make install # Install the necessary files
