language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
            - cmake
            - valgrind
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && BUILD_TYPE=Debug"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && BUILD_TYPE=Release"
    - os: osx
      osx_image: xcode9.2 
      compiler: clang
      env:
        - MATRIX_EVAL="BUILD_TYPE=Debug"
    - os: osx
      osx_image: xcode9.2 
      compiler: clang
      env:
        - MATRIX_EVAL="BUILD_TYPE=Release"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=ON ..

script:
  - cmake --build . # Build the code
  - |
    if [ "$BUILD_TYPE" == "Debug" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then # Run tests
      ctest -T memcheck # Check for memory leaks using Valgrind
    else
      ctest
    fi
  - sudo make install # Install the necessary files
