version: "0.1.{build}"

os:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf input

install:
  - git submodule update --init --recursive

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - mkdir build && cd build
  - cmake -A%PLATFORM% -DBUILD_TESTS=On ..

build_script:
  - cmake --build . --config %CONFIGURATION% -- %MSBUILD_ARGS% # Run the build
  - ctest --verbose -C %CONFIGURATION% # Test the code
  - cmake --build . --config %CONFIGURATION% --target INSTALL -- %MSBUILD_ARGS% # Install the files

test_script:
  - ctest --verbose -C %CONFIGURATION%
