version: "0.1.{build}"

os:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf input

install:
  - git submodule update --init --recursive

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - mkdir -p build
  - cd build
  - cmake .. -A%PLATFORM%

build:
  project: build\$(APPVEYOR_PROJECT_NAME).sln
  parallel: true
  verbosity: normal

test_script:
  - ctest --verbose -C %CONFIGURATION%
